name: Windows

on:
  workflow_dispatch:
  schedule:
    - cron: '0 23 * * 1'

jobs:
  tests:
    runs-on: windows-latest
    name: Windows CPython ${{ matrix.python-version }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build and install
      run: |
        pip install pip --upgrade
        pip install ".[test]" --verbose 

    - name: Test
      run: |
        cd tests
        pytest -vv
